### ISSUE TITLE
Password placeholders show dots

### ISSUE THREAD

**Issue by craigdallimore** [enigma-io/react-input-placeholder#14]
Hi - first off, great library!

I've noticed that in browsers that support `placeholder` natively, the `[type="password"]` inputs will show cleartext placeholders.

However, using this polyfill the placeholder content is rendered as a string of dots:

![](http://g.recordit.co/6glRo2GTlS.gif)

I've looked at changing the `type` of the fallback input to `text` while it is under the `(!value)` condition and it works reasonably:

![](http://g.recordit.co/d9XKamULiD.gif)

I'm curious to know what you think of such a solution - the top concern for me would be that changing the type will break any selector that uses `[type="password"]`. Happy to make a PR if you are more interested.

**Comment by quantizor** [comment]
@craigdallimore That's the only solution that I believe will work for a single input field, since the way we simulate the placeholder is to physically input the value.

An alternative though is to actually create 2 input fields and stack them on top of each other. The lower one would be the placeholder and the upper would be the actual input. Then the upper would not have a placeholder and you would need to listen for input events on the upper to dismiss the value of the lower.

Make sense?

**Comment by craigdallimore** [comment]
@yaycmyk I'm offering the former solution - seems to me both ways we'd be putting a `[type="text"]` into the DOM, so users will need to be mindful of their selectors - and I expect they already are, as this lib provides a `placeholder` class to help with styling.
